Не получается подконнектить Visa
YarNik/ort-javabase pull request #1
Opened 2016-12-02 15:19 UTC by YarNik

2016-12-18 12:27 UTC, strazhkoe requested changes

2016-12-18 12:27 UTC, strazhkoe commented on Homework/src/gmail/yarnik75/module8/Passport/ForeignPassport.java
> +	private Visa[] Visas = new Visa[2];
название поля должно начинаться с _ и маленькой буквы

2016-12-18 12:27 UTC, strazhkoe commented on Homework/src/gmail/yarnik75/module8/Passport/Visa.java
> +	private int _periodOfStay; // ���� ���������� � ������
Почините кодировку

2016-12-18 12:27 UTC, strazhkoe commented on Homework/src/gmail/yarnik75/module8/Array/Array.java
> +	public void del(int x){
при удалении нужно уменьшать выделенную память под массив

2016-12-18 12:27 UTC, strazhkoe commented on Homework/src/gmail/yarnik75/module8/Array/Array.java
> +	public void print(){
метод печати отсюда  нужно убрать в main

2016-12-18 12:27 UTC, strazhkoe commented on Homework/src/gmail/yarnik75/module8/Array/Array.java
> +public class Array {
У массива нет методов для чтения данных. Должны присутствовать все CRUD операции (Create Read Update Delete)

2016-12-18 12:27 UTC, strazhkoe commented on Homework/src/gmail/yarnik75/module8/Passport/Visa.java
> +	public String getcountry() {
в именах слова надо разделять регистром символов. getCountry

2017-01-17 21:10 UTC, strazhkoe commented
Что с этим пул-реквестом? Закрываем его? Все задачи перенесены в другие?

2017-01-20 09:28 UTC, YarNik commented
Да, закрываем.
Задачи перенесены в другие ветви.


2017-01-17 23:10 GMT+02:00 Yevhen Strazhko <notifications@github.com>:

> Что с этим пул-реквестом? Закрываем его? Все задачи перенесены в другие?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/YarNik/ort-javabase/pull/1#issuecomment-273300405>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AXGTr9GzpI3MLesckEtyVGS9ZZ1DhfYVks5rTS40gaJpZM4LCqE2>
> .
>

2017-01-20 09:29 UTC, closed without merging